package domainwriter

const (
	DOMAIN_FOLDER     = "domain"
	MODEL_FOLDER      = "model"
	USECASE_FOLDER    = "usecase"
	PORT_FOLDER       = "port"
	ADAPTER_FOLDER    = "adapter"
	CONTROLLER_FOLDER = "controller"
	REPOSITORY_FOLDER = "repository"

	DOMAIN_PATH  = DOMAIN_FOLDER
	USECASE_PATH = DOMAIN_PATH + "/" + USECASE_FOLDER
	MODEL_PATH   = DOMAIN_PATH + "/" + MODEL_FOLDER
	PORT_PATH    = DOMAIN_PATH + "/" + PORT_FOLDER

	CONTROLLER_PATH = PORT_PATH + "/" + CONTROLLER_FOLDER
	REPOSITORY_PATH = PORT_PATH + "/" + REPOSITORY_FOLDER

	ADAPTER_PATH = ADAPTER_FOLDER
)
